// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using SkincareProductSalesSystem.Repositories.Models;

namespace SkincareProductSalesSystem.Repositories.Database;

public partial class SP25_NET1721_RPR231_PRJ_G1_SkincareProductSalesSystemDBContext : DbContext
{
    public SP25_NET1721_RPR231_PRJ_G1_SkincareProductSalesSystemDBContext()
    {
    }

    public SP25_NET1721_RPR231_PRJ_G1_SkincareProductSalesSystemDBContext(DbContextOptions<SP25_NET1721_RPR231_PRJ_G1_SkincareProductSalesSystemDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BlogPost> BlogPosts { get; set; }

    public virtual DbSet<Brand> Brands { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }

    public virtual DbSet<CustomerProfile> CustomerProfiles { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Promotion> Promotions { get; set; }

    public virtual DbSet<PromotionUsage> PromotionUsages { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<RoutineProduct> RoutineProducts { get; set; }

    public virtual DbSet<SkinCareRoutine> SkinCareRoutines { get; set; }

    public virtual DbSet<SkinTestQuestion> SkinTestQuestions { get; set; }
    public virtual DbSet<SkinTestOption> SkinTestOptions { get; set; }


    public virtual DbSet<SkinType> SkinTypes { get; set; }

    public virtual DbSet<User> Users { get; set; }

    

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnectionString")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

 

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BlogPost>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__BlogPost__AA1260385DF445CD");

            entity.Property(e => e.PostId)
                .HasMaxLength(100)
                .HasColumnName("PostID");
            entity.Property(e => e.AuthorId)
                .HasMaxLength(100)
                .HasColumnName("AuthorID");
            entity.Property(e => e.BlogCategory).IsRequired();
            entity.Property(e => e.Content).IsRequired();
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasColumnName("ImageURL");
            entity.Property(e => e.Title).IsRequired();
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Author).WithMany(p => p.BlogPosts)
                .HasForeignKey(d => d.AuthorId)
                .HasConstraintName("FK__BlogPosts__Autho__440B1D61");
        });

        modelBuilder.Entity<Brand>(entity =>
        {
            entity.HasKey(e => e.BrandId).HasName("PK__Brand__DAD4F05E519720C7");

            entity.ToTable("Brand");

            entity.Property(e => e.BrandId).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.Status).HasMaxLength(10);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Category__19093A0B5F2AF4D7");

            entity.ToTable("Category", tb => tb.HasTrigger("TR_Category_UpdatedAt"));

            entity.HasIndex(e => e.ParentCategoryId, "IX_Category_ParentCategoryId");

            entity.Property(e => e.CategoryId).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ParentCategoryId).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ParentCategory).WithMany(p => p.InverseParentCategory)
                .HasForeignKey(d => d.ParentCategoryId)
                .HasConstraintName("FK_Category_ParentCategory");
        });

        modelBuilder.Entity<CustomerAddress>(entity =>
        {
            entity.HasKey(e => e.CustomerAddressId).HasName("PK__Customer__DB891B7836966F15");

            entity.ToTable("CustomerAddress");

            entity.Property(e => e.CustomerAddressId).HasMaxLength(100);
            entity.Property(e => e.AddressType).HasMaxLength(50);
            entity.Property(e => e.DefaultAddress)
                .IsRequired()
                .HasDefaultValueSql("('0')");
            entity.Property(e => e.District).HasMaxLength(50);
            entity.Property(e => e.Province).HasMaxLength(50);
            entity.Property(e => e.ReceiverPhoneNumber).HasMaxLength(20);
            entity.Property(e => e.Street).HasMaxLength(50);
            entity.Property(e => e.Ward).HasMaxLength(50);
        });

        modelBuilder.Entity<CustomerProfile>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64D82DD1193F");

            entity.ToTable("CustomerProfile");

            entity.HasIndex(e => e.Email, "IX_CustomerProfile_Email");

            entity.HasIndex(e => e.SkinTypeId, "IX_CustomerProfile_SkinTypeId");

            entity.HasIndex(e => e.Email, "UQ_CustomerProfile_Email").IsUnique();

            entity.HasIndex(e => e.Phone, "UQ_CustomerProfile_Phone").IsUnique();

            entity.Property(e => e.CustomerId).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.IsSubscribed).HasDefaultValue(false);
            entity.Property(e => e.LoyaltyPoints).HasDefaultValue(0);
            entity.Property(e => e.Phone).HasMaxLength(20);
            entity.Property(e => e.PreferredPaymentMethod).HasMaxLength(50);
            entity.Property(e => e.SkinTypeId).HasMaxLength(100);
            entity.Property(e => e.UserId).HasMaxLength(100);

            entity.HasOne(d => d.SkinType).WithMany(p => p.CustomerProfiles)
                .HasForeignKey(d => d.SkinTypeId)
                .HasConstraintName("FK_CustomerProfile_SkinType");

            entity.HasOne(d => d.User).WithMany(p => p.CustomerProfiles)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_CustomerProfile_User");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Order__C3905BCFE04B1E45");

            entity.ToTable("Order", tb => tb.HasTrigger("TR_Order_UpdatedAt"));

            entity.HasIndex(e => e.CustomerId, "IX_Order_CustomerId");

            entity.HasIndex(e => e.OrderDate, "IX_Order_OrderDate");

            entity.HasIndex(e => e.Status, "IX_Order_Status");

            entity.Property(e => e.OrderId).HasMaxLength(100);
            entity.Property(e => e.CustomerAddressId).HasMaxLength(100);
            entity.Property(e => e.CustomerId).HasMaxLength(100);
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentMethod).HasMaxLength(50);
            entity.Property(e => e.ShippingFee).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status).HasMaxLength(50);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.TrackingNumber).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.CustomerAddress).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerAddressId)
                .HasConstraintName("FK__Order__CustomerA__0F624AF8");

            entity.HasOne(d => d.Customer).WithMany(p => p.Orders)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Order_CustomerProfile");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasKey(e => e.OrderDetailId).HasName("PK__OrderDet__D3B9D36C96BC29B2");

            entity.ToTable("OrderDetail", tb => tb.HasTrigger("TR_OrderDetail_UpdatedAt"));

            entity.HasIndex(e => e.OrderId, "IX_OrderDetail_OrderId");

            entity.HasIndex(e => e.ProductId, "IX_OrderDetail_ProductId");

            entity.Property(e => e.OrderDetailId).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Discount)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsReviewed).HasDefaultValue(false);
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.OrderId).HasMaxLength(100);
            entity.Property(e => e.ProductId).HasMaxLength(100);
            entity.Property(e => e.UnitPrice).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_OrderDetail_Order");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_OrderDetail_Product");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__9B556A3830DE1928");

            entity.ToTable("Payment");

            entity.HasIndex(e => e.OrderId, "UQ__Payment__C3905BCE904A0A72").IsUnique();

            entity.Property(e => e.PaymentId).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.OrderId)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PaymentAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PaymentDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentMethodId).HasMaxLength(100);
            entity.Property(e => e.PaymentStatus)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TransactionId).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithOne(p => p.Payment)
                .HasForeignKey<Payment>(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Payment_Order");

            entity.HasOne(d => d.PaymentMethod).WithMany(p => p.Payments)
                .HasForeignKey(d => d.PaymentMethodId)
                .HasConstraintName("FK__Payment__Payment__236943A5");
        });

        modelBuilder.Entity<PaymentMethod>(entity =>
        {
            entity.HasKey(e => e.PaymentMethodId).HasName("PK__PaymentM__DC31C1D39B66D204");

            entity.ToTable("PaymentMethod");

            entity.Property(e => e.PaymentMethodId).HasMaxLength(100);
            entity.Property(e => e.Name).HasMaxLength(100);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Product__B40CC6CD0BB21816");

            entity.ToTable("Product", tb => tb.HasTrigger("TR_Product_UpdatedAt"));

            entity.HasIndex(e => e.CategoryId, "IX_Product_CategoryId");

            entity.HasIndex(e => e.IsActive, "IX_Product_IsActive");

            entity.HasIndex(e => e.Name, "IX_Product_Name");

            entity.Property(e => e.ProductId).HasMaxLength(100);
            entity.Property(e => e.BrandId).HasMaxLength(100);
            entity.Property(e => e.CategoryId).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.StockQuantity).HasDefaultValue(0);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Brand).WithMany(p => p.Products)
                .HasForeignKey(d => d.BrandId)
                .HasConstraintName("FK__Product__BrandId__571DF1D5");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Product_Category");

            entity.HasMany(d => d.SkinTypes).WithMany(p => p.Products)
                .UsingEntity<Dictionary<string, object>>(
                    "ProductSkinType",
                    r => r.HasOne<SkinType>().WithMany()
                        .HasForeignKey("SkinTypeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ProductSkinType_SkinType"),
                    l => l.HasOne<Product>().WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_ProductSkinType_Product"),
                    j =>
                    {
                        j.HasKey("ProductId", "SkinTypeId").HasName("PK__ProductS__1951EFAD26042475");
                        j.ToTable("ProductSkinType");
                        j.IndexerProperty<string>("ProductId").HasMaxLength(100);
                        j.IndexerProperty<string>("SkinTypeId").HasMaxLength(100);
                    });
        });

        modelBuilder.Entity<Promotion>(entity =>
        {
            entity.HasKey(e => e.PromotionId).HasName("PK__Promotio__52C42FCFDB3986B8");

            entity.ToTable("Promotion");

            entity.HasIndex(e => e.Code, "IX_Promotion_Code");

            entity.HasIndex(e => e.IsActive, "IX_Promotion_IsActive");

            entity.HasIndex(e => e.Code, "UQ_Promotion_Code").IsUnique();

            entity.Property(e => e.PromotionId).HasMaxLength(100);
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MinimumPurchase).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.StartDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<PromotionUsage>(entity =>
        {
            entity.HasKey(e => e.UsageId).HasName("PK__Promotio__29B19720BC886A48");

            entity.ToTable("PromotionUsage");

            entity.HasIndex(e => e.OrderId, "IX_PromotionUsage_OrderId");

            entity.HasIndex(e => e.PromotionId, "IX_PromotionUsage_PromotionId");

            entity.Property(e => e.UsageId).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.DiscountAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.IsValid).HasDefaultValue(true);
            entity.Property(e => e.Notes).HasMaxLength(500);
            entity.Property(e => e.OrderId).HasMaxLength(100);
            entity.Property(e => e.PromotionId).HasMaxLength(100);
            entity.Property(e => e.UsedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Order).WithMany(p => p.PromotionUsages)
                .HasForeignKey(d => d.OrderId)
                .HasConstraintName("FK_PromotionUsage_Order");

            entity.HasOne(d => d.Promotion).WithMany(p => p.PromotionUsages)
                .HasForeignKey(d => d.PromotionId)
                .HasConstraintName("FK_PromotionUsage_Promotion");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Review__74BC79CE31801353");

            entity.ToTable("Review");

            entity.HasIndex(e => e.CustomerId, "IX_Review_CustomerId");

            entity.HasIndex(e => e.IsVisible, "IX_Review_IsVisible");

            entity.HasIndex(e => e.ProductId, "IX_Review_ProductId");

            entity.Property(e => e.ReviewId).HasMaxLength(100);
            entity.Property(e => e.Comment).HasMaxLength(1000);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CustomerId).HasMaxLength(100);
            entity.Property(e => e.ImageUrl).HasMaxLength(255);
            entity.Property(e => e.IsVerified).HasDefaultValue(false);
            entity.Property(e => e.IsVisible).HasDefaultValue(true);
            entity.Property(e => e.ProductId).HasMaxLength(100);
            entity.Property(e => e.PurchaseDate).HasColumnType("datetime");

            entity.HasOne(d => d.Customer).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Review_CustomerProfile");

            entity.HasOne(d => d.Product).WithMany(p => p.Reviews)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_Review_Product");
        });

        modelBuilder.Entity<RoutineProduct>(entity =>
        {
            entity.HasKey(e => e.RoutineProductId).HasName("PK__RoutineP__901DE1BCF531F53F");

            entity.ToTable("RoutineProduct");

            entity.Property(e => e.RoutineProductId).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Frequency).HasMaxLength(50);
            entity.Property(e => e.IsRequired).HasDefaultValue(true);
            entity.Property(e => e.ProductId).HasMaxLength(100);
            entity.Property(e => e.RoutineId).HasMaxLength(100);
            entity.Property(e => e.Step).HasMaxLength(100);
            entity.Property(e => e.TimeOfDay).HasMaxLength(50);
            entity.Property(e => e.UsageInstructions).HasMaxLength(500);

            entity.HasOne(d => d.Product).WithMany(p => p.RoutineProducts)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_RoutineProduct_Product");

            entity.HasOne(d => d.Routine).WithMany(p => p.RoutineProducts)
                .HasForeignKey(d => d.RoutineId)
                .HasConstraintName("FK_RoutineProduct_Routine");
        });

        modelBuilder.Entity<SkinCareRoutine>(entity =>
        {
            entity.HasKey(e => e.RoutineId).HasName("PK__SkinCare__A6E3E4FA69B86AC5");

            entity.ToTable("SkinCareRoutine", tb => tb.HasTrigger("TR_SkinCareRoutine_UpdatedAt"));

            entity.HasIndex(e => e.SkinTypeId, "IX_SkinCareRoutine_SkinTypeId");

            entity.Property(e => e.RoutineId).HasMaxLength(100);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Duration).HasMaxLength(50);
            entity.Property(e => e.EveningSteps).HasMaxLength(1000);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.MorningSteps).HasMaxLength(1000);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.SkinTypeId).HasMaxLength(100);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.WeeklySteps).HasMaxLength(1000);

            entity.HasOne(d => d.SkinType).WithMany(p => p.SkinCareRoutines)
                .HasForeignKey(d => d.SkinTypeId)
                .HasConstraintName("FK_SkinCareRoutine_SkinType");
        });

        modelBuilder.Entity<SkinTestQuestion>(entity =>
        {
            entity.HasKey(e => e.QuestionId).HasName("PK_SkinTestQuestion");

            entity.ToTable("SkinTestQuestion");

            entity.Property(e => e.QuestionId)
                .HasMaxLength(100);

            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(500);

            entity.Property(e => e.QuestionOrder)
                .IsRequired();
               

            entity.Property(e => e.IsActive)
                .HasDefaultValue(true);

            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("GETDATE()")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<SkinTestOption>(entity =>
        {
            entity.HasKey(e => e.OptionId).HasName("PK_SkinTestOption");

            entity.ToTable("SkinTestOption");

            entity.Property(e => e.OptionId)
                .HasMaxLength(100);

            entity.Property(e => e.QuestionId)
                .HasMaxLength(100);

            entity.Property(e => e.OptionText)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.SkinTypeId)
                .HasMaxLength(100);

            entity.HasOne(d => d.Question)
                .WithMany(p => p.SkinTestOptions)
                .HasForeignKey(d => d.QuestionId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_SkinTestOption_SkinTestQuestion");

            entity.HasOne(d => d.SkinType)
                .WithMany(p => p.SkinTestOptions)
                .HasForeignKey(d => d.SkinTypeId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_SkinTestOption_SkinType");
        });


        modelBuilder.Entity<SkinType>(entity =>
        {
            entity.HasKey(e => e.SkinTypeId).HasName("PK__SkinType__D5D2960BCCBAAAD6");

            entity.ToTable("SkinType");

            entity.HasIndex(e => e.Name, "UQ_SkinType_Name").IsUnique();

            entity.Property(e => e.SkinTypeId).HasMaxLength(100);
            entity.Property(e => e.AvoidIngredients).HasMaxLength(500);
            entity.Property(e => e.CareInstructions).HasMaxLength(1000);
            entity.Property(e => e.Characteristics).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RecommendedIngredients).HasMaxLength(500);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__User__1788CC4CCBDF1E16");

            entity.ToTable("User", tb => tb.HasTrigger("TR_User_UpdatedAt"));

            entity.HasIndex(e => e.Email, "IX_User_Email");

            entity.HasIndex(e => e.IsActive, "IX_User_IsActive");

            entity.HasIndex(e => e.PhoneNumber, "IX_User_PhoneNumber");

            entity.HasIndex(e => e.RoleName, "IX_User_RoleName");

            entity.HasIndex(e => e.Username, "IX_User_Username");

            entity.HasIndex(e => e.Email, "UQ_User_Email").IsUnique();

            entity.HasIndex(e => e.Username, "UQ_User_Username").IsUnique();

            entity.Property(e => e.UserId).HasMaxLength(100);
            entity.Property(e => e.Avatar).HasMaxLength(255);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.FullName).HasMaxLength(50);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.IsEmailVerified).HasDefaultValue(false);
            entity.Property(e => e.IsPhoneVerified).HasDefaultValue(false);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PasswordSalt)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.RefreshToken).HasMaxLength(255);
            entity.Property(e => e.RefreshTokenExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .HasDefaultValue("Customer");
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50);
        });
      
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}