// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SkincareProductSalesSystem.Repositories.Models;

public partial class User
{
	[Key]
	//[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public string UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string Avatar { get; set; }

    public bool? IsEmailVerified { get; set; }

    public bool? IsPhoneVerified { get; set; }

    public string RefreshToken { get; set; }

    public DateTime? RefreshTokenExpiryDate { get; set; }

    public bool? IsActive { get; set; }

    public string RoleName { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<BlogPost> BlogPosts { get; set; } = new List<BlogPost>();

    public virtual ICollection<CustomerProfile> CustomerProfiles { get; set; } = new List<CustomerProfile>();
}